SUBROUTINE TRIANGULARSUP(A, B, X, N)
IMPLICIT NONE 

INTEGER, INTENT(IN) :: N
DOUBLE PRECISION, DIMENSION(N,N), INTENT(IN) :: A
DOUBLE PRECISION, DIMENSION(N), INTENT(IN) :: B
DOUBLE PRECISION, DIMENSION(N), INTENT(OUT) :: X

DOUBLE PRECISION :: SOMA
INTEGER :: I, J

X(N) = B(N) / A(N,N)

DO I = N - 1, 1, -1
    SOMA = B(I)
    DO J = I + 1, N
        SOMA = SOMA - (A(I,J) * X(J))
    END DO
    X(I) = SOMA / A(I,I)
END DO	

END SUBROUTINE TRIANGULARSUP